name = "MinecraftTweaked"
author = "[LunaPixelStudios, Sidpatchy]"
version = "35.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "497caa6dd042775e377233171b151696bb7d0c67f8869c4cc089ffffbdb7bfbb"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
