name = "MinecraftTweaked"
author = "[LunaPixelStudios, Sidpatchy]"
version = "35.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b94da162835f51c2952c3ba07f4b028c4226cbb6107c2e3e1fb60343fd93fdd1"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
