name = "MinecraftTweaked"
author = "[LunaPixelStudios, Sidpatchy]"
version = "35.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "675f7239166795f37637c93497032ba75970e5f4a291a70b5c1ae31a04ff91eb"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
