name = "MinecraftTweaked"
author = "[LunaPixelStudios, Sidpatchy]"
version = "35.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9a12ad3c2977f2039bfea89609c241822ba21dde2af3ad35538fdbee85b3b15"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
