name = "MinecraftTweaked"
author = "[LunaPixelStudios, Sidpatchy]"
version = "35.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd0febee14f4ba424b1b135454f18114d8601266979e75b8bd469e802fd23ace"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
