name = "MinecraftTweaked"
author = "[LunaPixelStudios, Sidpatchy]"
version = "35.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "966898366c842962e872af4dcff89f6aac1f22d51d9e8ff47cba20754d24e05d"

[versions]
forge = "36.2.22"
minecraft = "1.16.5"
