name = "Additional Bars [FORGE]"
filename = "1.16.5-additionalbars-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3290/973/1.16.5-additionalbars-2.0.3.jar"
hash-format = "murmur2"
hash = "3018097506"

[update]
[update.curseforge]
file-id = 3290973
project-id = 357362
