name = "Additional Banners"
filename = "AdditionalBanners-1.16.5-6.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3279/597/AdditionalBanners-1.16.5-6.0.3.jar"
hash-format = "murmur2"
hash = "2259965122"

[update]
[update.curseforge]
file-id = 3279597
project-id = 230137
