name = "Additional Banners"
filename = "AdditionalBanners-1.16.5-6.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/557/AdditionalBanners-1.16.5-6.0.4.jar"
hash-format = "murmur2"
hash = "3157892509"

[update]
[update.curseforge]
file-id = 3348557
project-id = 230137
