name = "AI Improvements"
filename = "AI-Improvements-1.16.5-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3533/942/AI-Improvements-1.16.5-0.4.0.jar"
hash-format = "murmur2"
hash = "3145014905"

[update]
[update.curseforge]
file-id = 3533942
project-id = 233019
