name = "Alex's Delight"
filename = "Alex's Delight 1.1.3 - Forge 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/931/Alex's Delight 1.1.3 - Forge 1.16.5.jar"
hash-format = "murmur2"
hash = "4252461400"

[update]
[update.curseforge]
file-id = 3600931
project-id = 556448
