name = "Applied Energistics 2 Wireless Terminals Forge"
filename = "ae2wtlib-0.3.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/234/ae2wtlib-0.3.2-1.16.5.jar"
hash-format = "murmur2"
hash = "3398427345"

[update]
[update.curseforge]
file-id = 3455234
project-id = 483310
