name = "Better Compatibility Checker"
filename = "BetterCompatibilityChecker-1.0.6-build.19+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/635/BetterCompatibilityChecker-1.0.6-build.19+mc1.16.5.jar"
hash-format = "murmur2"
hash = "96544167"

[update]
[update.curseforge]
file-id = 3575635
project-id = 551894
