name = "Better Compatibility Checker"
filename = "BetterCompatibilityChecker-1.0.7-build.22+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/132/BetterCompatibilityChecker-1.0.7-build.22+mc1.16.5.jar"
hash-format = "murmur2"
hash = "1726861292"

[update]
[update.curseforge]
file-id = 3596132
project-id = 551894
