name = "Beyond Earth"
filename = "Space-BossTools-1.16.5-5.5e.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3581/611/Space-BossTools-1.16.5-5.5e.jar"
hash-format = "murmur2"
hash = "873328540"

[update]
[update.curseforge]
file-id = 3581611
project-id = 377448
