name = "Blue Skies"
filename = "blue_skies-1.16.5-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3411/324/blue_skies-1.16.5-1.1.3.jar"
hash-format = "murmur2"
hash = "3007247976"

[update]
[update.curseforge]
file-id = 3411324
project-id = 312918
