name = "Campful"
filename = "campful-1.16.5-3.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3230/821/campful-1.16.5-3.1.0.jar"
hash-format = "murmur2"
hash = "1111534944"

[update]
[update.curseforge]
file-id = 3230821
project-id = 429901
