name = "CatLib"
filename = "CatLib-Forge-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/501/CatLib-Forge-1.8.jar"
hash-format = "murmur2"
hash = "1508443308"

[update]
[update.curseforge]
file-id = 3590501
project-id = 513391
