name = "CB Multipart"
filename = "CBMultipart-1.16.5-3.0.4.123-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/708/CBMultipart-1.16.5-3.0.4.123-universal.jar"
hash-format = "murmur2"
hash = "3042631890"

[update]
[update.curseforge]
file-id = 3601708
project-id = 258426
