name = "Chicken Chunks 1.8.+"
filename = "ChickenChunks-1.16.5-2.9.1.89-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/96/ChickenChunks-1.16.5-2.9.1.89-universal.jar"
hash-format = "murmur2"
hash = "1784305336"

[update]
[update.curseforge]
file-id = 3596096
project-id = 243883
