name = "Compat O' Plenty"
filename = "Compat-O-Plenty-1.16.5-1.0.5-(No-Pantries).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3607/903/Compat-O-Plenty-1.16.5-1.0.5-(No-Pantries).jar"
hash-format = "murmur2"
hash = "3916429633"

[update]
[update.curseforge]
file-id = 3607903
project-id = 558850
