name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.2.491.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/919/CraftTweaker-1.16.5-7.1.2.491.jar"
hash-format = "murmur2"
hash = "629083377"

[update]
[update.curseforge]
file-id = 3627919
project-id = 239197
