name = "Create Stuff Additions"
filename = "create-stuff-additions1.16.5_v1.1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/933/create-stuff-additions1.16.5_v1.1.6.jar"
hash-format = "murmur2"
hash = "2268381609"

[update]
[update.curseforge]
file-id = 3615933
project-id = 466792
