name = "Create Crafts & Additions"
filename = "createaddition-1.16.5-20211215b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/777/createaddition-1.16.5-20211215b.jar"
hash-format = "murmur2"
hash = "2226575509"

[update]
[update.curseforge]
file-id = 3567777
project-id = 439890
