name = "Create Crafts & Additions"
filename = "createaddition-1.16.5-20220129a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/494/createaddition-1.16.5-20220129a.jar"
hash-format = "murmur2"
hash = "3648266829"

[update]
[update.curseforge]
file-id = 3629494
project-id = 439890
