name = "Darker Depths"
filename = "darkerdepths-1.16.5-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3458/10/darkerdepths-1.16.5-1.1.4.jar"
hash-format = "murmur2"
hash = "2814663276"

[update]
[update.curseforge]
file-id = 3458010
project-id = 460681
