name = "Dead Guys Untitled Deep Dark"
filename = "deepdark_4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3611/76/deepdark_4.2.jar"
hash-format = "murmur2"
hash = "2389469782"

[update]
[update.curseforge]
file-id = 3611076
project-id = 479009
