name = "Drippy Loading Screen [Forge]"
filename = "drippyloadingscreen_forge_1.5.1_MC_1.16.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/868/drippyloadingscreen_forge_1.5.1_MC_1.16.2-1.16.5.jar"
hash-format = "murmur2"
hash = "3814004107"

[update]
[update.curseforge]
file-id = 3630868
project-id = 511770
