name = "Dungeons Libraries"
filename = "dungeons_libraries-1.16.5-0.0.3-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/373/dungeons_libraries-1.16.5-0.0.3-beta.jar"
hash-format = "murmur2"
hash = "2917486501"

[update]
[update.curseforge]
file-id = 3546373
project-id = 550941
