name = "Dungeons Mobs"
filename = "dungeons_mobs-1.16.5-1.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3418/599/dungeons_mobs-1.16.5-1.0.10.jar"
hash-format = "murmur2"
hash = "1301064481"

[update]
[update.curseforge]
file-id = 3418599
project-id = 428883
