name = "Enchanting Infuser [Forge]"
filename = "EnchantingInfuser-v1.0.2-1.16.5-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3596/539/EnchantingInfuser-v1.0.2-1.16.5-Forge.jar"
hash-format = "murmur2"
hash = "2758313051"

[update]
[update.curseforge]
file-id = 3596539
project-id = 551151
