name = "Entity Culling Fabric/Forge"
filename = "entityculling-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/824/entityculling-1.3.0.jar"
hash-format = "murmur2"
hash = "558202955"

[update]
[update.curseforge]
file-id = 3358824
project-id = 448233
