name = "Entity Culling Fabric/Forge"
filename = "entityculling-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3221/962/entityculling-1.0.2.jar"
hash-format = "murmur2"
hash = "1373606438"

[update]
[update.curseforge]
file-id = 3221962
project-id = 448233
