name = "Equipment Compare"
filename = "EquipmentCompare-1.16.5-1.2.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3494/718/EquipmentCompare-1.16.5-1.2.7.jar"
hash-format = "murmur2"
hash = "734315862"

[update]
[update.curseforge]
file-id = 3494718
project-id = 502561
