name = "Falling Leaves (Forge)"
filename = "Fallingleaves-1.16.3-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3603/314/Fallingleaves-1.16.3-1.2.3.jar"
hash-format = "murmur2"
hash = "623749333"

[update]
[update.curseforge]
file-id = 3603314
project-id = 463155
