name = "FTB Chunks (Forge)"
filename = "ftb-chunks-forge-1605.3.2-build.115.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3603/374/ftb-chunks-forge-1605.3.2-build.115.jar"
hash-format = "murmur2"
hash = "1977919156"

[update]
[update.curseforge]
file-id = 3603374
project-id = 314906
