name = "FTB Ranks (Forge)"
filename = "ftb-ranks-forge-1605.1.5-build.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3530/24/ftb-ranks-forge-1605.1.5-build.16.jar"
hash-format = "murmur2"
hash = "3476518925"

[update]
[update.curseforge]
file-id = 3530024
project-id = 314905
