name = "Iceberg"
filename = "Iceberg-1.16.5-1.0.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/915/Iceberg-1.16.5-1.0.38.jar"
hash-format = "murmur2"
hash = "766682618"

[update]
[update.curseforge]
file-id = 3609915
project-id = 520110
