name = "Illagers Wear Armor"
filename = "illagersweararmor-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3462/24/illagersweararmor-1.0.5.jar"
hash-format = "murmur2"
hash = "863603767"

[update]
[update.curseforge]
file-id = 3462024
project-id = 407488
