name = "Immersive FX"
filename = "ImmersiveFX 1.0.0-1 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/610/ImmersiveFX 1.0.0-1 1.16.5.jar"
hash-format = "murmur2"
hash = "3308974959"

[update]
[update.curseforge]
file-id = 3590610
project-id = 563495
