name = "Immersive FX"
filename = "ImmersiveFX 1.0.1 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/435/ImmersiveFX 1.0.1 1.16.5.jar"
hash-format = "murmur2"
hash = "641626753"

[update]
[update.curseforge]
file-id = 3604435
project-id = 563495
