name = "In Control!"
filename = "incontrol-1.16-5.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3513/646/incontrol-1.16-5.2.2.jar"
hash-format = "murmur2"
hash = "1025406272"

[update]
[update.curseforge]
file-id = 3513646
project-id = 257356
