name = "Konkrete [Forge]"
filename = "konkrete_forge_1.3.2_MC_1.16.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3555/621/konkrete_forge_1.3.2_MC_1.16.2-1.16.5.jar"
hash-format = "murmur2"
hash = "3568661424"

[update]
[update.curseforge]
file-id = 3555621
project-id = 410295
