name = "Kotlin for Forge"
filename = "kotlinforforge-1.16.0-obf.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3527/736/kotlinforforge-1.16.0-obf.jar"
hash-format = "murmur2"
hash = "3392051400"

[update]
[update.curseforge]
file-id = 3527736
project-id = 351264
