name = "L_Ender 's Cataclysm"
filename = "Cataclysm-0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/899/Cataclysm-0.11.jar"
hash-format = "murmur2"
hash = "2276824233"

[update]
[update.curseforge]
file-id = 3606899
project-id = 551586
