name = "Large Fluid Tank"
filename = "LargeFluidTank-16.1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3363/989/LargeFluidTank-16.1.8.jar"
hash-format = "murmur2"
hash = "3422365973"

[update]
[update.curseforge]
file-id = 3363989
project-id = 291006
