name = "Litematica Forge Port"
filename = "litematica-forge-1.16.5-0.0.0-dev.20210606.150444.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3394/523/litematica-forge-1.16.5-0.0.0-dev.20210606.150444.jar"
hash-format = "murmur2"
hash = "253801253"

[update]
[update.curseforge]
file-id = 3394523
project-id = 506506
