name = "Magnesium Extras"
filename = "magnesium_extras-mc1.16.5_v1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/543/magnesium_extras-mc1.16.5_v1.3.1.jar"
hash-format = "murmur2"
hash = "953016961"

[update]
[update.curseforge]
file-id = 3592543
project-id = 558905
