name = "Miner's Helmet"
filename = "mining_helmet-1.16.5-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3273/200/mining_helmet-1.16.5-2.0.1.jar"
hash-format = "murmur2"
hash = "3899747143"

[update]
[update.curseforge]
file-id = 3273200
project-id = 351948
