name = "More Minecarts and Rails"
filename = "moreminecarts-1.3.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3621/632/moreminecarts-1.3.14.jar"
hash-format = "murmur2"
hash = "2543451737"

[update]
[update.curseforge]
file-id = 3621632
project-id = 440845
