name = "More Minecarts and Rails"
filename = "moreminecarts-1.3.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/322/moreminecarts-1.3.13.jar"
hash-format = "murmur2"
hash = "3506169246"

[update]
[update.curseforge]
file-id = 3591322
project-id = 440845
