name = "More Villagers"
filename = "morevillagers-FORGE-1.16.5-1.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3466/80/morevillagers-FORGE-1.16.5-1.5.5.jar"
hash-format = "murmur2"
hash = "1856990533"

[update]
[update.curseforge]
file-id = 3466080
project-id = 484954
