name = "MrCrayfish's More Furniture Mod"
filename = "morecfm-1.3.1-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/602/morecfm-1.3.1-1.16.3.jar"
hash-format = "murmur2"
hash = "3325796312"

[update]
[update.curseforge]
file-id = 3346602
project-id = 486928
