name = "Mutant More"
filename = "mutantmore-1.16.5-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/386/mutantmore-1.16.5-1.0.0.jar"
hash-format = "murmur2"
hash = "2149857057"

[update]
[update.curseforge]
file-id = 3504386
project-id = 539994
