name = "Nature Expansion"
filename = "Nature Expansion1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/538/Nature Expansion1.4.1.jar"
hash-format = "murmur2"
hash = "640270211"

[update]
[update.curseforge]
file-id = 3609538
project-id = 481562
