name = "Nether's Exoticism"
filename = "nether-s-exoticism-1.16.5-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3594/245/nether-s-exoticism-1.16.5-1.1.4.jar"
hash-format = "murmur2"
hash = "319751778"

[update]
[update.curseforge]
file-id = 3594245
project-id = 486029
