name = "Not Enough Energistics"
filename = "NotEnoughEnergistics-1.16.5-0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/291/NotEnoughEnergistics-1.16.5-0.1.jar"
hash-format = "murmur2"
hash = "4265872514"

[update]
[update.curseforge]
file-id = 3566291
project-id = 515565
