name = "Aquamirae"
filename = "Aquamirae 2.2 (1.16.5).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/955/Aquamirae 2.2 (1.16.5).jar"
hash-format = "murmur2"
hash = "1638088689"

[update]
[update.curseforge]
file-id = 3549955
project-id = 536254
