name = "Ore Stone Variants"
filename = "OSV-Forge-7.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/510/OSV-Forge-7.5.jar"
hash-format = "murmur2"
hash = "1784384847"

[update]
[update.curseforge]
file-id = 3612510
project-id = 287538
