name = "Ore Stone Variants"
filename = "OSV-Forge-7.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/405/OSV-Forge-7.4.jar"
hash-format = "murmur2"
hash = "1774237405"

[update]
[update.curseforge]
file-id = 3587405
project-id = 287538
