name = "Outvoted"
filename = "outvoted-2.0.0-alpha.13.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3552/993/outvoted-2.0.0-alpha.13.1.jar"
hash-format = "murmur2"
hash = "1365380158"

[update]
[update.curseforge]
file-id = 3552993
project-id = 415057
