name = "Paintings ++"
filename = "paintings-1.16.4-7.0.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3131/44/paintings-1.16.4-7.0.0.1.jar"
hash-format = "murmur2"
hash = "23021103"

[update]
[update.curseforge]
file-id = 3131044
project-id = 252042
