name = "Personality"
filename = "personality-1.16.5-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/549/personality-1.16.5-1.0.3.jar"
hash-format = "murmur2"
hash = "1017221582"

[update]
[update.curseforge]
file-id = 3549549
project-id = 415974
