name = "Polymorph (Forge)"
filename = "polymorph-forge-1.16.5-0.39.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/756/polymorph-forge-1.16.5-0.39.jar"
hash-format = "murmur2"
hash = "2226636189"

[update]
[update.curseforge]
file-id = 3604756
project-id = 388800
