name = "Project Red - Core"
filename = "ProjectRed-1.16.5-4.10.0-core.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/713/ProjectRed-1.16.5-4.10.0-core.jar"
hash-format = "murmur2"
hash = "1387962433"

[update]
[update.curseforge]
file-id = 3407713
project-id = 228702
