name = "Project Red - Illumination"
filename = "ProjectRed-1.16.5-4.11.0-beta-6-illumination.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3535/646/ProjectRed-1.16.5-4.11.0-beta-6-illumination.jar"
hash-format = "murmur2"
hash = "158713644"

[update]
[update.curseforge]
file-id = 3535646
project-id = 229046
