name = "Project Red - Exploration"
filename = "ProjectRed-1.16.5-4.10.0-exploration.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/716/ProjectRed-1.16.5-4.10.0-exploration.jar"
hash-format = "murmur2"
hash = "4281282834"

[update]
[update.curseforge]
file-id = 3407716
project-id = 229049
