name = "Project Red - Integration"
filename = "ProjectRed-1.16.5-4.11.0-beta-6-integration.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3535/645/ProjectRed-1.16.5-4.11.0-beta-6-integration.jar"
hash-format = "murmur2"
hash = "2794221153"

[update]
[update.curseforge]
file-id = 3535645
project-id = 229045
