name = "Pyromancer"
filename = "pyromancer 1.7.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3608/459/pyromancer 1.7.0.3.jar"
hash-format = "murmur2"
hash = "1390544390"

[update]
[update.curseforge]
file-id = 3608459
project-id = 471135
