name = "Pyromancer"
filename = "pyromancer 1.6.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3438/199/pyromancer 1.6.3.jar"
hash-format = "murmur2"
hash = "287938411"

[update]
[update.curseforge]
file-id = 3438199
project-id = 471135
