name = "Refined Pipes"
filename = "refinedpipes-0.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/290/refinedpipes-0.5.2.jar"
hash-format = "murmur2"
hash = "4277053299"

[update]
[update.curseforge]
file-id = 3630290
project-id = 370696
