name = "Restored Earth"
filename = "restored_earth-1.16.5-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/628/restored_earth-1.16.5-1.3.0.jar"
hash-format = "murmur2"
hash = "3355295370"

[update]
[update.curseforge]
file-id = 3566628
project-id = 523197
