name = "Screenshot to Clipboard (Forge)"
filename = "screenshot-to-clipboard-1.0.7-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3509/44/screenshot-to-clipboard-1.0.7-forge.jar"
hash-format = "murmur2"
hash = "1887679032"

[update]
[update.curseforge]
file-id = 3509044
project-id = 326950
