name = "Slimy Stuff"
filename = "slimy-stuff-1.16.5-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/19/slimy-stuff-1.16.5-1.0.6.jar"
hash-format = "murmur2"
hash = "3537597421"

[update]
[update.curseforge]
file-id = 3570019
project-id = 514266
