name = "spark"
filename = "spark-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3337/641/spark-forge.jar"
hash-format = "murmur2"
hash = "3681000633"

[update]
[update.curseforge]
file-id = 3337641
project-id = 361579
