name = "Stalwart Dungeons"
filename = "stalwart-dungeons-1.16.5-1.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3495/397/stalwart-dungeons-1.16.5-1.1.7.jar"
hash-format = "murmur2"
hash = "1541760492"

[update]
[update.curseforge]
file-id = 3495397
project-id = 474817
