name = "SuperMartijn642's Core Lib"
filename = "supermartijn642corelib-1.0.15-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/827/supermartijn642corelib-1.0.15-mc1.16.5.jar"
hash-format = "murmur2"
hash = "4274465498"

[update]
[update.curseforge]
file-id = 3543827
project-id = 454372
