name = "Tetra Pak"
filename = "tetrapak-1.16.5-0.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/988/tetrapak-1.16.5-0.3.3.jar"
hash-format = "murmur2"
hash = "3881505979"

[update]
[update.curseforge]
file-id = 3456988
project-id = 463554
