name = "Tetra"
filename = "tetra-1.16.5-3.20.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3585/32/tetra-1.16.5-3.20.0.jar"
hash-format = "murmur2"
hash = "2019755418"

[update]
[update.curseforge]
file-id = 3585032
project-id = 289712
