name = "The Abyss II - The Other Side"
filename = "TheAbyss2 2.2.2 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3625/426/TheAbyss2 2.2.2 1.16.5.jar"
hash-format = "murmur2"
hash = "1493504910"

[update]
[update.curseforge]
file-id = 3625426
project-id = 440647
