name = "The Abyss II - The Other Side"
filename = "TheAbyss2 2.0.0-1 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/721/TheAbyss2 2.0.0-1 1.16.5.jar"
hash-format = "murmur2"
hash = "2449120032"

[update]
[update.curseforge]
file-id = 3590721
project-id = 440647
