name = "The Outer End"
filename = "OuterEnd-0.2.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3404/58/OuterEnd-0.2.14.jar"
hash-format = "murmur2"
hash = "2346284930"

[update]
[update.curseforge]
file-id = 3404058
project-id = 430404
