name = "The Lost Cities"
filename = "lostcities-1.16-4.0.11-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/586/lostcities-1.16-4.0.11-beta.jar"
hash-format = "murmur2"
hash = "3582994909"

[update]
[update.curseforge]
file-id = 3606586
project-id = 269024
