name = "Tinker's Delight"
filename = "TinkersDelight-1.16-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3555/216/TinkersDelight-1.16-1.8.jar"
hash-format = "murmur2"
hash = "3618270495"

[update]
[update.curseforge]
file-id = 3555216
project-id = 490440
