name = "Tips"
filename = "Tips-1.16.5-4.0.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/215/Tips-1.16.5-4.0.15.jar"
hash-format = "murmur2"
hash = "59028392"

[update]
[update.curseforge]
file-id = 3604215
project-id = 306549
