name = "Towers of the Wild: Additions"
filename = "totw_additions-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/277/totw_additions-1.1.0.jar"
hash-format = "murmur2"
hash = "701969095"

[update]
[update.curseforge]
file-id = 3579277
project-id = 560091
