name = "Trading Post [Forge]"
filename = "TradingPost-v1.0.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3509/565/TradingPost-v1.0.2-1.16.5.jar"
hash-format = "murmur2"
hash = "2649228874"

[update]
[update.curseforge]
file-id = 3509565
project-id = 539057
