name = "Traveler's Index"
filename = "travelers_index-1.16.4-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3132/23/travelers_index-1.16.4-1.0.2.jar"
hash-format = "murmur2"
hash = "4077954888"

[update]
[update.curseforge]
file-id = 3132023
project-id = 418863
