name = "Upgraded Core"
filename = "upgradedcore-1.16.5-1.0.0.3-release.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/769/upgradedcore-1.16.5-1.0.0.3-release.jar"
hash-format = "murmur2"
hash = "523750365"

[update]
[update.curseforge]
file-id = 3622769
project-id = 566700
