name = "Village Artifacts"
filename = "villagertools-1.16.5-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3528/18/villagertools-1.16.5-1.0.2.jar"
hash-format = "murmur2"
hash = "189157728"

[update]
[update.curseforge]
file-id = 3528018
project-id = 469301
