name = "Void Totem"
filename = "voidtotem-1.16.5-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3327/88/voidtotem-1.16.5-1.4.0.jar"
hash-format = "murmur2"
hash = "1584481062"

[update]
[update.curseforge]
file-id = 3327088
project-id = 449655
