name = "Wandering Bag"
filename = "wandering-bag-1.16.5-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3615/82/wandering-bag-1.16.5-1.0.3.jar"
hash-format = "murmur2"
hash = "1515435024"

[update]
[update.curseforge]
file-id = 3615082
project-id = 500434
