name = "When Dungeons Arise - Forge!"
filename = "DungeonsArise-1.16.5-2.1.47-release.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3392/240/DungeonsArise-1.16.5-2.1.47-release.jar"
hash-format = "murmur2"
hash = "276310465"

[update]
[update.curseforge]
file-id = 3392240
project-id = 442508
