name = "Wyrmroost"
filename = "Wyrmroost-1.16.3-1.2.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3173/775/Wyrmroost-1.16.3-1.2.11.jar"
hash-format = "murmur2"
hash = "872715395"

[update]
[update.curseforge]
file-id = 3173775
project-id = 340333
