name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.1.2_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/499/Xaeros_Minimap_22.1.2_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "3582580176"

[update]
[update.curseforge]
file-id = 3630499
project-id = 263420
