name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.0_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/293/XaerosWorldMap_1.20.0_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "1742996971"

[update]
[update.curseforge]
file-id = 3613293
project-id = 317780
