name = "XP Tome"
filename = "xptome-1.16.5-v2.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3320/406/xptome-1.16.5-v2.1.2.jar"
hash-format = "murmur2"
hash = "2856762180"

[update]
[update.curseforge]
file-id = 3320406
project-id = 344787
